### ISSUE TITLE
Invalid character causes build error in Windows

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom.github.io#39]
Either [whats-next-in-lagom-1-2](https://github.com/lagom/lagom.github.io/blob/template/src/blog/whats-next-in-lagom-1-2.md) or [microservices-from-development-to-production](https://github.com/lagom/lagom.github.io/blob/template/src/blog/microservices-from-development-to-production.md) contain a character that's not valid on Windows default encoding causing the MD processor to fail and break the build preventing Windows users from running the site locally.

I suspect it's the fancy quotes in [microservices-from-development-to-production](https://github.com/lagom/lagom.github.io/blob/template/src/blog/microservices-from-development-to-production.md).

**Comment by rstento** [comment]
Here are the messages from a bad build:
[info] Loading global plugins from C:\Users\rsten\.sbt\0.13\plugins
[info] Loading project definition from C:\lagom.github.io\project
[info] Updating {file:/C:/lagom.github.io/project/}lagom-github-io-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c                                                                                           [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to lagom-docs (in build file:/C:/lagom.github.io/)
> webStage
[info] Updating {file:/C:/lagom.github.io/}lagom-docs...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.play:twirl-api_2.11:1.1.1 -> 1.3.0
[warn]  * org.webjars:jquery:(2.1.1, 1.10.2, 1.7.2) -> 2.2.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Stylus compiling on 1 source(s)
[info] Compiling 29 Scala sources to C:\lagom.github.io\target\scala-2.11\classes                                                                                           ...
[info] Optimizing 1 JavaScript(s) with Uglify
[info]
[info] Building 2 concat group(s)
[warn] C:\lagom.github.io\src\main\scala\com\lightbend\lagom\docs\BlogMetaDataPar                                                                                           ser.scala:144: non-variable type argument String in type pattern java.util.Map[St                                                                                           ring,AnyRef] is unchecked since it is eliminated by erasure
[warn]       case map: java.util.Map[String, AnyRef] => new Yaml(map.asScala.toMa                                                                                           p.mapValues(yamlToScala))
[warn]                           ^
[warn] C:\lagom.github.io\src\main\scala\com\lightbend\lagom\docs\BlogMetaDataPar                                                                                           ser.scala:145: non-variable type argument AnyRef in type pattern java.util.List[A                                                                                           nyRef] is unchecked since it is eliminated by erasure
[warn]       case list: java.util.List[AnyRef] => list.asScala.toList.map(yamlToS                                                                                           cala)
[warn]                            ^
[warn] there were two deprecation warnings; re-run with -deprecation for details
[warn] three warnings found
[info] Running com.lightbend.lagom.docs.DocumentationGenerator C:\lagom.github.io                                                                                           \target\web\generated-html C:\lagom.github.io\src\docs C:\lagom.github.io\src\mai                                                                                           n\markdown C:\lagom.github.io\src\blog 0dd0e63632731c8308ee99907e5e12d04167b2a4
[error] (run-main-0) java.nio.charset.UnmappableCharacterException: Input length                                                                                            = 1
java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.sc                                                                                           ala:72)
        at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:862)
        at scala.collection.Iterator$$anon$18.skip(Iterator.scala:627)
        at scala.collection.Iterator$$anon$18.hasNext(Iterator.scala:630)
        at com.lightbend.lagom.docs.BlogMetaDataParser$IteratorOps.nextOption(Blo                                                                                           gMetaDataParser.scala:21)
        at com.lightbend.lagom.docs.BlogMetaDataParser$.extractFrontMatter(BlogMe                                                                                           taDataParser.scala:69)
        at com.lightbend.lagom.docs.BlogMetaDataParser$.parsePostFrontMatter(Blog                                                                                           MetaDataParser.scala:33)
        at com.lightbend.lagom.docs.Blog$$anonfun$2.apply(Blog.scala:16)
        at com.lightbend.lagom.docs.Blog$$anonfun$2.apply(Blog.scala:13)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.                                                                                           scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.                                                                                           scala:245)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized                                                                                           .scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.lightbend.lagom.docs.Blog$.findBlogPosts(Blog.scala:13)
        at com.lightbend.lagom.docs.DocumentationGenerator$.delayedEndpoint$com$l                                                                                           ightbend$lagom$docs$DocumentationGenerator$1(DocumentationGenerator.scala:82)
        at com.lightbend.lagom.docs.DocumentationGenerator$delayedInit$body.apply                                                                                           (DocumentationGenerator.scala:17)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:1                                                                                           2)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(Traversabl                                                                                           eForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.lightbend.lagom.docs.DocumentationGenerator$.main(DocumentationGen                                                                                           erator.scala:17)
        at com.lightbend.lagom.docs.DocumentationGenerator.main(DocumentationGene                                                                                           rator.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 27 s, completed Mar 2, 2017 10:57:10 AM
